So, it's `github.event.release.prerelease` instead of `github.event.release.prereleased` that you need to use in your workflow.
Re-enable submission with CRAN.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -74,7 +74,6 @@ runs:
         
         if [[ "${{ github.event_name }}" == "release" ]]; then
           echo "Is prerelease: ${{ github.event.release.prerelease }}"
-          echo "Is prereleased: ${{ github.event.release.prereleased }}"
           echo "Release tag: ${{ github.event.release.tag_name }}"
           echo "Release name: ${{ github.event.release.name }}"
         fi
@@ -276,24 +275,24 @@ runs:
         echo "Submitting package to CRAN..."
 
         # Pass all collected metadata to the script to avoid re-reading DESCRIPTION
-        #Rscript ${{ github.action_path }}/scripts/submit-to-cran.R \
-        #  "${PKG_FILE}" \
-        #  "." \
-        #  "${PKGNAME}" \
-        #  "${VERSION}" \
-        #  "${MAINTAINER_NAME}" \
-        #  "${MAINTAINER_EMAIL}"
-        #
-        ## Check if the script was successful
-        #if [ $? -eq 0 ]; then
-        #  echo "CRAN submission successful!"
-        #  echo "submission_status=success" >> $GITHUB_OUTPUT
-        #else
-        #  echo "CRAN submission failed"
-        #  echo "submission_status=failed" >> $GITHUB_OUTPUT
-        #  echo "submission_reason=upload_failed" >> $GITHUB_OUTPUT
-        #  exit 1
-        #fi
+        Rscript ${{ github.action_path }}/scripts/submit-to-cran.R \
+          "${PKG_FILE}" \
+          "." \
+          "${PKGNAME}" \
+          "${VERSION}" \
+          "${MAINTAINER_NAME}" \
+          "${MAINTAINER_EMAIL}"
+        
+        # Check if the script was successful
+        if [ $? -eq 0 ]; then
+          echo "CRAN submission successful!"
+          echo "submission_status=success" >> $GITHUB_OUTPUT
+        else
+          echo "CRAN submission failed"
+          echo "submission_status=failed" >> $GITHUB_OUTPUT
+          echo "submission_reason=upload_failed" >> $GITHUB_OUTPUT
+          exit 1
+        fi
 
     - name: Create issue content file
       if: inputs.create-issue == 'true'
